config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

   resources :investments
   post 'investments/parsing', to: "investments#parsing", as: "parsing"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/investment.rb
class Investment < ApplicationRecord

  validates :name, :isin, :emetteur, :quantity, :price, presence: true
  def gain(investment)
    position_start = investment.price * investment.quantity
    position_actual = investment.value * investment.quantity
    gain = position_actual - position_start
    return gain
  end
end

app/models/user.rb
class User < ApplicationRecord
  # has_many :positions, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!

end

app/controllers/investments_controller.rb
class InvestmentsController < ApplicationController

  require 'open-uri'
  require 'nokogiri'


  def new
    @investment = Investment.new
  end

  def create
    @investment = Investment.new(investment_params)

    if @investment.save && params[:commit] == 'Créer la position'
      redirect_to root_path
      flash[:notice] = "Votre position a bien été enregistré."
    elsif @investment.save && params[:commit] == 'Créer une autre position'
      redirect_to new_investment_path
      flash[:notice] = "Votre position a bien été enregistré."
    else
      render :new
      flash[:alert] = "Veuillez compléter le formulaire s'il vous plaît."
    end
  end

  def parsing
    require 'open-uri'
    require 'nokogiri'

    @investments = Investment.all
    @investments.each do |investment|
      # if investment.emetteur == "SG"
        url = "https://live.euronext.com/en/product/structured-products/DE000SD09RZ3-XMLI"
        html_file = open(url).read
        html_doc = Nokogiri::HTML(html_file)
        result = html_doc.search("div.date-header span.data-60").text
        investment.value = result.to_f
        raise
        investment.save
      # elsif investment.emetteur == "BNP"
      #   url = "https://bourse.societegenerale.fr/retail/Products-ProductSearcgQuick/q-#{investment.isin}"
      #   html_file = open(url).read
      #   html_doc = Nokogiri::HTML(html_file)
      #   result = html_doc.search('.productPriceBid .hidePush').text.strip
      #   result = result.gsub(",", ".")
      #   investment.value = result.to_f
      #   investment.save
      # else
      #   url = "https://fr.citifirst.com/FR/Produits/Turbos/#{investment.name}/#{investment.isin}/"
      #   html_file = open(url).read
      #   html_doc = Nokogiri::HTML(html_file)
      #   result = html_doc.search('.Ask .Value').span.to_s
      #   raise
      #   result = result.gsub(",", ".")
      #   investment.value = result.to_f
      #   investment.save
      # end
    end
    redirect_to root_path
  end

  # def edit
  #   @product = Product.find(params[:id])
  # end

  # def update
  #   @product = Product.find(params[:id])
  #   if @product.update(product_params)
  #     redirect_to selection_path(@product.selection)
  #   else render :edit
  #   end
  # end

  # def destroy
  #   @product = Product.find(params[:id])
  #   @product.destroy
  #   redirect_to selection_path(@product.selection)
  # end

  # def sold_status
  #   product = Product.find(params[:id])
  #   product.status = "vendu"
  #   product.save
  #   redirect_to selection_path(product.selection)
  # end

  # def tosell_status
  #   product = Product.find(params[:id])
  #   product.status = "à vendre"
  #   product.save
  #   redirect_to selection_path(product.selection)
  # end

  # def return_status
  #   product = Product.find(params[:id])
  #   product.status = "retourné"
  #   product.save
  #   redirect_to selection_path(product.selection)
  # end

  # def edit_price
  #   @product = Product.find(params[:id])
  # end

  # def change_price
  #   @product = Product.find(params[:id])
  #   @product.update(price_params)
  #   @product.save
  #   redirect_to selection_path(@product.selection)
  #   flash[:notice] = "Votre prix a bien été modifié."
  # end

  private

  def investment_params
    params.require(:investment).permit(:name, :isin, :emetteur, :quantity, :price)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @investments = Investment.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/investments/new.html.erb
<div class="background">
  <div class="wrapper">
    <h3 id="title-wrapper">Créer une nouvelle position</h3>
    <div class="">
      <% investment = Investment.new %>
      <%= simple_form_for(investment) do |f| %>
        <div class="">
          <%= f.input :name, label: 'Nom du sous-jacent', placeholder: "exemple : Tesla, Apple, CAC40..." %>
          <%= f.input :isin, label: 'Code ISIN', placeholder: "exemple : DE000SB587A4" %>
          <%= f.input :emetteur, label: 'Emetteur du produit', collection: ["SG", "BNP", "CITI"] %>
          <div style="display:flex; justify-content: space-between; margin-bottom: 6px;">
            <%= f.label "Prix de revient unique en €" %>
            <%= f.number_field :price%>
          </div>
          <div style="display:flex; justify-content: space-between; margin-bottom: 6px;">
            <%= f.label "Quantité achetée" %>
            <%= f.number_field :quantity%>
          </div>
         </div>
         <div class="form-button" style="display:flex; justify-content: space-between;">
          <%= f.submit "Créer la position", class: 'button' %>
          <%= f.submit "Créer une autre position", class: 'button' %>
         </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Turbowallet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="background">
  <div class="wrapper">
    <%= link_to parsing_path, method: :post, id:"icon_refresh" do%>
      <i class="fas fa-sync-alt"></i>
    <% end %>
    <%= link_to new_investment_path, id:"icon_plus" do%>
      <i class="fas fa-plus"></i>
    <% end %>
    <h3 id="title-wrapper">Votre Portefeuille Titres</h3>
    <% if @investments.present? %>
    <table class="table">
      <tr>
        <td>Ss-jacent</td>
        <td>Isin</td>
        <td>Emetteur</td>
        <td>PRU</td>
        <td>Qté</td>
        <td>Cours</td>
        <td>+/- value</td>
      </tr>
      <% @investments.each do |investment| %>
        <tr>
            <td><%= investment.name %></td>
            <td><%= investment.isin %></td>
            <td><%= investment.emetteur %></td>
            <td><%= investment.price %>€</td>
            <td><%= investment.quantity %></td>
            <td><%= investment.value %>€</td>
            <% if investment.gain(investment) >= 0 %>
              <td id="positive-value"><p><%= investment.gain(investment) %>€</p></td>
            <% else %>
              <td id="negative-value"><p><%= investment.gain(investment) %>€</p></td>
            <% end %>
        </tr>
      <% end %>
    </table>
    <% else %>
      <p>Votre portefeuille est actuellement vide.</p>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>